name: Container Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .

        - name: Scan with Trivy and Generate Report
        run: |
          # Create reports directory first
          mkdir -p ./reports
          # Run scan and output to file
          trivy image --format sarif --output ./reports/trivy-report.sarif my-app:${{ github.sha }}
          # Verify file was created
          ls -la ./reports/
      
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: ./reports/trivy-report.sarif