name: Security Scan Matrix

on: [push, workflow_dispatch]

jobs:
  scan-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [critical, medium, clean]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Test Image
        run: docker build -t test-image -f Dockerfile.${{ matrix.image }} .
          
      - name: Run Trivy Scan
        run: |
          mkdir -p ./reports
          trivy image \
            --severity CRITICAL,HIGH \
            --exit-code ${{ matrix.image == 'critical' && '1' || '0' }} \
            --format sarif \
            --output ./reports/trivy-${{ matrix.image }}.sarif \
            test-image
          
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: ./reports/trivy-*.sarif

      - name: Validate Results
        run: |
          chmod +x .github/scripts/validate-scan.sh
          ./.github/scripts/validate-scan.sh ${{ matrix.image }} 